name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello world!"
          echo "Heyy, i am back"
          echo "From, local"
      - name: Print Bye
        run: echo "Good Bye!"
